### ISSUE TITLE
how to combine actions?

### ISSUE THREAD

**Issue by rileylnapier** [tomatau/type-to-reducer#14]
one thing that i like about the switch statement is the ability to stack actions.  with this library, i don't see a good way to do it besides creating a bunch of helper functions.

any thoughts on how to make it easier?

**Comment by tomatau** [comment]
Yes you're right, it doesn't have the same capability for following through on a switch statement, although some do consider that dangerous. You can write the reducer as a separate function instead of inline however.

```js
const updateFooReducer = (state, action) => ({ ...state, foo: action.payload })

const reducer = typeToReducer({
  [FOO]: {
    [CHANGE]: updateFooReducer,
    [MODIFY]: updateFooReducer,
    [UPDATE]: updateFooReducer,
    [TWEAK]: updateFooReducer,
  }
})
```
